### ISSUE TITLE
cool site

### ISSUE THREAD

**Issue by julescarbon** [gre/wavegl#1]
this thing is great, i made this with it today hope you like it!
https://gist.github.com/julescarbon/28d710a881315b59a2e3

**Comment by gre** [comment]
awesome!

About the project, we need to polish the UI a bit 
and improve some stuff 
and we are going to release it soon ;-)

**Comment by hughsk** [comment]
Yeah this is awesome @gre, nice work! Look forward to release :D You guys should jump on `#stackgl` on freenode IRC if you guys are interested in following the gl-modules stuff :)

**Comment by gre** [comment]
Thanks :-)

I've just released a new UI with also better perfs!

**So the main idea is to have this pipeline: `GLSL (GPU) -> readPixels -> WebAudioAPI (Audio Card)`. No overhead of JS, pipe an Uint8Array from the GPU to the Audio Card !**

The idea is a hack at the start but they could be some real potential :-)
The GLSL have limitation for such hack usage though :-D After like 2 minutes you will start notice some noise in the sound, well that is due to float imprecision (I also had to use a float in second instead of an int sample number) + there is no support for binary logic operator so we can't make ByteBeat + Latency is an issue if you want to have user interaction.

2 important things that we should improved in the current version:
- **modularity** : using glslify we can implement tiny module (e.g; the audio-envelope module) that we can import from any song. I don't know how to do that only client-side though. I've took the concatenation approach so far.
- **support for user uniforms**: for instance you want to inject some notes from the external.

**Comment by hughsk** [comment]
Ooh been meaning to get glslify working client-side, will have another look tonight and let you know how that goes! :)

**Comment by hughsk** [comment]
@gre I got it working!

You can use the new [glslify-api](http://github.com/stackgl/glslify-api) module with browserify to bundle shaders on the fly in the browser, [requirebin](http://requirebin.com/)-style. I'm hosting a copy of the API which the above module defaults to, so you can keep using static hosting too. Can use [gl-shader-update](http://github.com/hughsk/gl-shader-update/) to recycle a shader, meaning you should just be able to do something along these lines and have it work:

``` javascript
var update = require('gl-shader-update')
var api    = require('glslify-api')()

editor.on('change', function() {
  api(editor.getValue(), function(err, src) {
    if (err) throw err

    update.frag(shader, src)
  })
})
```

No obligation to use it of course, I've got a few projects which need this too – but hopefully it helps :)

**Comment by gre** [comment]
Awesome!
